name: scit
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - openblas
  - libcxx
  - numpy
  - pillow
  - pytorch=1.12
  - torchvision
  - torchaudio
  - typing_extensions
  - certifi
  - ca-certificates
  - openssl
  - readline
  - sqlite
  - tk
  - xz
  - zlib
  - bzip2
  - freetype
  - jpeg
  - libpng
  - libtiff
  - brotlipy
  - cffi
  - cryptography
  - idna
  - pyopenssl
  - pysocks
  - requests
  - urllib3
  - charset-normalizer
  - pycparser
  - six
  - ffmpeg
  - giflib
  - gmp
  - gnutls
  - lame
  - lcms2
  - lerc
  - libdeflate
  - libedit
  - libffi
  - libiconv
  - libidn2
  - libunistring
  - libuv
  - libwebp
  - lz4-c
  - ncurses
  - nettle
  - openh264
  - zstd
